# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MineSweep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MineSweep
  pod 'Masonry'
  
  target 'MineSweepTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MineSweepUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
